import assert from 'node:assert/strict';
import test from 'node:test';
import {
  countSolutions,
  EMPTY_GRID,
  findConflicts,
  formatGrid,
  isFull,
  isSolved,
  parseGrid,
  SAMPLE_PUZZLE,
  solve,
} from './sudoku.ts';

function toGrid(str) {
  return [...str].map(Number);
}

test('an empty grid solves to a full, valid, conflict-free Sudoku', () => {
  const solved = solve(EMPTY_GRID.slice());
  assert.ok(solved);
  assert.ok(isFull(solved));
  assert.equal(findConflicts(solved).size, 0);
  assert.ok(isSolved(solved));
});

test('every row, column and box of a solved grid is a permutation of 1-9', () => {
  const g = solve(EMPTY_GRID.slice());
  const permOf1to9 = (cells) => assert.deepEqual([...cells].sort((a, b) => a - b), [1, 2, 3, 4, 5, 6, 7, 8, 9]);
  for (let r = 0; r < 9; r++) permOf1to9(g.slice(r * 9, r * 9 + 9));
  for (let c = 0; c < 9; c++) permOf1to9(Array.from({ length: 9 }, (_, r) => g[r * 9 + c]));
  for (let b = 0; b < 9; b++) {
    const br = Math.floor(b / 3) * 3;
    const bc = (b % 3) * 3;
    const cells = [];
    for (let r = br; r < br + 3; r++) for (let c = bc; c < bc + 3; c++) cells.push(g[r * 9 + c]);
    permOf1to9(cells);
  }
});

test('a puzzle generated by removing cells from a solved grid is solved back to the same completion', () => {
  const full = solve(EMPTY_GRID.slice());
  // remove every 3rd cell (leaves a clue-rich, quick-to-solve puzzle)
  const puzzle = full.map((v, i) => (i % 3 === 0 ? 0 : v));
  const resolved = solve(puzzle);
  assert.ok(resolved);
  // every originally-given clue must be preserved
  for (let i = 0; i < 81; i++) {
    if (puzzle[i]) assert.equal(resolved[i], puzzle[i]);
  }
  assert.ok(isSolved(resolved));
});

test('the classic sample puzzle is solvable, valid and has a unique solution', () => {
  assert.equal(SAMPLE_PUZZLE.length, 81);
  const grid = toGrid(SAMPLE_PUZZLE);
  assert.equal(findConflicts(grid).size, 0);
  const solved = solve(grid);
  assert.ok(solved);
  assert.ok(isSolved(solved));
  for (let i = 0; i < 81; i++) if (grid[i]) assert.equal(solved[i], grid[i]);
  assert.equal(countSolutions(grid, 5), 1);
});

test('a grid with an immediate duplicate is rejected, not solved', () => {
  const bad = EMPTY_GRID.slice();
  bad[0] = 5;
  bad[1] = 5; // two 5s in the same row
  assert.ok(findConflicts(bad).has(0));
  assert.ok(findConflicts(bad).has(1));
  assert.equal(solve(bad), null);
  assert.equal(countSolutions(bad), 0);
});

test('a wrong-length grid is rejected without throwing', () => {
  assert.equal(solve([1, 2, 3]), null);
  assert.equal(countSolutions([1, 2, 3]), 0);
});

test('countSolutions caps out rather than exhaustively enumerating a very open grid', () => {
  // an almost-empty grid has astronomically many solutions; the cap must apply
  const n = countSolutions(EMPTY_GRID.slice(), 2);
  assert.equal(n, 2);
});

test('parseGrid accepts dots or zeros for blanks and ignores formatting characters', () => {
  const dotted = SAMPLE_PUZZLE.replace(/0/g, '.');
  const withFormatting = dotted.replace(/(.{9})/g, '$1\n').replace(/(.{3})/g, '$1|');
  const r1 = parseGrid(dotted);
  const r2 = parseGrid(withFormatting);
  assert.ok(r1.ok);
  assert.ok(r2.ok);
  assert.deepEqual(r1.grid, r2.grid);
  assert.deepEqual(r1.grid, toGrid(SAMPLE_PUZZLE));
});

test('parseGrid rejects the wrong cell count with a helpful error', () => {
  const short = parseGrid('12345');
  assert.equal(short.ok, false);
  assert.match(short.error, /81/);
});

test('formatGrid round-trips with parseGrid', () => {
  const grid = toGrid(SAMPLE_PUZZLE);
  const text = formatGrid(grid);
  const back = parseGrid(text);
  assert.ok(back.ok);
  assert.deepEqual(back.grid, grid);
});

test('isFull / isSolved distinguish a complete grid from a merely full-but-conflicting one', () => {
  const solved = solve(EMPTY_GRID.slice());
  assert.ok(isFull(solved) && isSolved(solved));
  const broken = solved.slice();
  broken[1] = broken[0]; // introduce a duplicate in row 0
  assert.ok(isFull(broken));
  assert.ok(!isSolved(broken));
});
